import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  const [todo, setTodo]=useState([]);
  const handleChange=(e)=>{
    setTodo(e.target.value);
  }
  const handleClick=()=>{
    fetch("http://localhost:3004/todos",{
      method:"POST",
      headers:{"Content-Type":"Application/json"},
      body:JSON.stringify({todo})
    })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         TODO APP
        </h1> 
        <br/>
        <br/>
      <div>
       <input type="text" placeholder="Enter Todo" onChange={handleChange}/>
       <button onClick={handleClick}>Add Todo</button>
       </div>
        <div className={styles.grid}> 
        

          <Link href="/tododisplay" className={styles.card}>
            <h2 style={{"border":"1px solid black", "padding":"20px", "backgroundColor":"lightBlue","cursor":"pointer" }}>Click here!.. to see all todo list</h2>
            
          </Link>

         
        </div>
      </main>


    </div>
  )
}
